car_sharing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
    path('register/', views.register, name="register"),
    path('logIn/', views.logIn, name="logIn"),
    path('logOut/', views.logOut, name='logOut'),
    path('PubRide/', views.PubRide, name='PubRide'),
    path('pickRide/', views.pickRide, name='pickRide'),
    path('yourRide/<int:user>/', views.yourRide, name='yourRide'),
    path('updateRide/<int:id>/', views.updateRide, name='updateRide'),
    path('riderInfo/<int:id>/', views.riderInfo, name='riderInfo'),
    path('rides/', views.rides, name='rides'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('editProfile/', views.editProfile, name='editProfile'),
    path('booking/<int:pk>/', views.booking, name='booking'),
    path('success/', views.success, name='success'),
    path('decrease_counter/<int:pk>/',
         views.decrease_counter, name='decrease_counter'),
    path('activate/<uidb64>/<token>/', views.activate, name="activate"),
    path('contact/', views.contact, name='contact'),
]

home/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, default=1, blank=True, null=True)
    # riders = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    car_name = models.CharField(max_length=120)
    date_of_trip = models.DateField(default=timezone.now)
    time_of_trip = models.TimeField(default=timezone.now)
    source = models.CharField(max_length=120)
    destination = models.CharField(max_length=120)
    vacant_seats = models.IntegerField()
    price= models.FloatField(default=0)
    # participants = models.ManyToManyField(User, blank=True)
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.source + " to " + self.destination


class Profile(models.Model):
    user = models.CharField(max_length=240)
    first_name = models.CharField(max_length=240)
    last_name = models.CharField(max_length=240)
    contact_no = models.CharField(max_length=240)
    email= models.EmailField(max_length=254, null=True, blank=True)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.first_name[0:100]
    
class Contact(models.Model):
    sno=models.AutoField(primary_key=True)
    name=models.CharField(max_length=40)
    email=models.CharField(max_length=40)
    phone=models.CharField(max_length=13)
    desc=models.TextField()
    time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name + '-' + self.email 

# This model is savig ride information
class Booking(models.Model):
    post=models.ForeignKey("Post", on_delete=models.CASCADE)
    riders_id=models.IntegerField(blank=True, null=True)
    seats_booked=models.IntegerField(blank=True, null=True, default=0)

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.db.models import F
from .models import *
from car_sharing import settings
from django.core.mail import send_mail, EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from .tokens import generate_token
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from datetime import datetime
import math
from django.contrib.auth.models import User


def home(request):
    context={}
    if request.user.is_authenticated:
        profile=User.objects.get(username=request.user)
        context={'profile':profile}
    return render(request, "homepage.html", context)

def pickRide(request):
    return render(request, "pickRide.html")

def yourRide(request, user):
    rides=Post.objects.filter(user=user)
    context={"rides":rides}
    return render(request, "yourRides.html", context)

def riderInfo(request, id):
    context={}
    bookings=[]
    user=[]
    allrides=Booking.objects.all()
    for ride in allrides:
        print(ride.post.id)
        if ride.post.id==id:
            bookings.append(ride.riders_id)
    
    riders_profile=User.objects.filter(id__in=bookings)

    context={'riders_profile':riders_profile}
    return render(request, "rider_info.html", context)

def updateRide(request, id):
    context={}
    if request.method=='POST':
        source = request.POST['source']
        destination = request.POST['destination']
        vacant_seats = request.POST['vacant_seats']
        date_of_trip = request.POST['date_of_trip']
        time_of_trip = request.POST['time_of_trip']
        price = request.POST['price']
        car_name = request.POST.get('car_name')
        ride=Post.objects.get(id=id)
        ride.source=source
        ride.destination=destination
        ride.date_of_trip=date_of_trip
        ride.time_of_trip=time_of_trip
        ride.vacant_seats=vacant_seats
        ride.car_name=car_name
        ride.price=price

        ride.save()
        print(request.user.id)

        messages.success(request, "Your Ride has been updated")

        # Here we are concatinating logged in user_id with url
        user_id=request.user.id
        url = '/yourRide/{}'.format(user_id)  # yourRide/{{logged_in_user_id}}
        return redirect(url)
    else:
        ride=Post.objects.get(id=id)
        context.update({"ride":ride})
    return render(request, "editRide.html", context)

def deleteRide(request, id):
    ride=Post.objects.get(id=id)
    
    if ride:
        ride.delete()

        messages.error(request, "Your Ride has been deleted")

        # Here we are concatinating logged in user_id with url
        user_id=request.user.id
        url = '/yourRide/{}'.format(user_id)  # yourRide/{{logged_in_user_id}}
        return redirect(url)
    else:
        messages.error(request, "Some Problem Occured! Your Ride cannot be deleted. Please try again!")
        return render(request, 'homepage.html')


def contact(request):
    if request.method=='POST':
        name= request.POST.get('name')
        email= request.POST.get('email')
        phone= request.POST.get('phone')
        desc= request.POST.get('desc')

        instance = Contact(name=name, email=email, phone=phone, desc=desc)
        instance.save()
        messages.success(request, "Your query has been saved")
    return render(request, "contact.html")


def PubRide(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            user=request.user
            source = request.POST['source']
            destination = request.POST['destination']
            vacant_seats = request.POST['vacant_seats']
            date_of_trip = request.POST['date_of_trip']
            time_of_trip = request.POST['time_of_trip']
            price = request.POST['price']
            car_name = request.POST.get('car_name')

            post1 = Post(
                user=user,source=source, destination=destination, vacant_seats=vacant_seats, date_of_trip=date_of_trip, time_of_trip=time_of_trip, price=price, car_name=car_name)

            post1.save()

            messages.success(request, "Your ride has been successfully posted")
            return render(request, "PubRide.html", {'username': request.user.username})
        else:
            messages.error(request, "Please login to post a ride.")
            return render(request, "logIn.html")
    return render(request, "PubRide.html")

def pagination(page, rides):
    # PAGINATION LOGIC STARTS
    # designing pagination logic
    no_of_posts=2
    # page= request.GET.get('page') # fetching value from url

    # By default, request.GET.get('page') returns string and if there is no page then return None
    # so if there is no page, make page = 1 otherwise convert ot integer
    if page is None:
        page = 1
    else:
        page = int(page)

    
    # counting all blogs in the databases to perform pagination logic
    length = len(rides)
    # here we are using python slicing function
    # below line just used to show how many blogs can be rendered on blog page and from where to where (ie, if page = 1, then blogs from index 0 to 2 will be displayed)
    rides = rides[(page-1)*no_of_posts: page*no_of_posts]

    # if page is greater than 1 then prev will be decremented by page-1 else make it None
    if page > 1:
        prev=page-1
    else:
        prev=None

    # Similarly, if page is less than ceiling value of required number of pages then nxt will be incremented by page+1 else make it None
    if page<math.ceil(length/no_of_posts):
        nxt=page+1
    else:
        nxt=None

    return rides, prev, nxt
    
    # PAGINATION LOGIC ENDS


def rides(request):
    if request.method == "POST":
        leave = request.POST.get('leave')
        arrive = request.POST.get('arrive')
        date = request.POST.get('date')
        # number_of_passengers so that we can pass it through url to use it on ride.html
        number = request.POST.get('number')
        lookup = (Q(source__icontains=leave) &
                  Q(destination__icontains=arrive))
        if leave != None and arrive != None and date != None and number != None:
            rides = Post.objects.filter(Q(lookup))

            # if vacant_seats is less than the user demand then we are not showing that particular ride and if date and time of trip is less than todays date and time
            for ride in rides:
                if ride.vacant_seats < int(number) or (ride.date_of_trip < datetime.now().date() and ride.time_of_trip < datetime.now().time()):
                    rides=rides.exclude(id = ride.id)
            
            # these blocks are for pagination 
            page= request.GET.get('page')
            rides, prev, nxt = pagination(page, rides)

            context={'rides': rides,'number':number, 'prev':prev, 'nxt':nxt}

            return render(request, "rides.html", context)
    else:
        rides=Post.objects.all()
        # if date and time of trip is less than todays date and time then we are not showing in all rides 
        for ride in rides:
            if ride.date_of_trip < datetime.now().date() and ride.time_of_trip < datetime.now().time():
                rides=rides.exclude(id = ride.id)

        # these blocks are for pagination 
        page= request.GET.get('page')
        rides, prev, nxt = pagination(page, rides)

        context={'rides': rides, 'prev':prev, 'nxt':nxt}

        return render(request, "allRides.html", context)

def booking(request, pk):
    if request.user.is_authenticated:
        bookings=Booking.objects.filter(riders_id=pk)

        context={'bookings':bookings}
        return render(request, "yourBookings.html", context)


def decrease_counter(request, pk):
    if request.method == "POST":
        ride = Post.objects.get(id=pk)
        # getting number_of_passenger through url get method
        number=request.GET.get('number')
        number=number if number else 1
        print(number)
        ride.vacant_seats = F('vacant_seats') - number
        ride.save()
        
        # This model is savig ride information
        bookings=Booking(post=ride, riders_id=request.user.id, seats_booked=number)
        bookings.save()

        return render(request, "success.html")


def success(request):
    return render(request, "success.html")


def register(request):
    if request.method == "POST":
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username):
            messages.error(
                request, "Username already exist! Please try some other username.")
            return render(request, "register.html")

        if User.objects.filter(email=email).exists():
            messages.error(request, "Email Already Registered!!")
            return render(request, "register.html")

        if len(username) > 20:
            messages.error(request, "Username must be under 20 charcters!!")
            return render(request, "register.html")

        if pass1 != pass2:
            messages.error(request, "Passwords didn't matched!!")
            return render(request, "register.html")

        if not username.isalnum():
            messages.error(request, "Username must be Alpha-Numeric!!")
            return render(request, "register.html")

        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name = first_name

home/templates/activation_failed.html
{% autoescape off %}

Activation failed, please try again.

{% endautoescape %}

home/templates/allRides.html
{% extends 'base.html' %}
{% load static %}

{% block allRidesactive %}active{% endblock allRidesactive %}

{% block head %}
<title>All Rides</title>
<!-- CSS script -->
<link rel="stylesheet" href="{% static 'rides.css' %}" />
{% endblock head %}

{% block content %}
    <div class="container">
        <h2 class="my-3 d-flex">Available Rides:-</h2>
        {% include 'rideCards.html' %}
    {% endblock %}

home/templates/contact.html
{% extends 'base.html' %}

{% block contactactive %}active{% endblock contactactive %}

{% block content %}
<section id="contact-us">
    <div class="container d-block">
        <h2>Contact Us</h2>
        <form action="{% url 'home:contact' %}" method="POST" class="text-left">
            {% csrf_token %}
            <div class="form-group pt-3">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Enter your name">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp"
                    placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                    else.</small>
            </div>

            <div class="form-group">
                <label for="phone">Phone Number</label>
                <input type="tel" name="phone" class="form-control" id="phone" placeholder="Enter your phone number">
            </div>

            <div class="form-group">
                <label for="desc">How may we help you?</label>
                <textarea class="form-control" name="desc" id="desc" rows="5"></textarea>
            </div>
            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>
</section>
{% endblock content %}

home/templates/editProfile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Edit Profile</title>
{% endblock head %}

{% block content %}
<section id="contact-us">
    <div class="container d-block">
        <h2>Edit Your Profile</h2>
        <form action="{% url 'home:editProfile' %}" method="POST" class="text-left" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group pt-3">
                <label for="user">Username</label>
                <input type="text" name="user" class="form-control" id="user" value="{{request.user}}" readonly>
            </div>
            <div class="form-group pt-3">
                <label for="first_name">First Name</label>
                <input type="text" name="first_name" class="form-control" id="first_name" value="{{request.user.first_name}}" readonly>
            </div>
            <div class="form-group pt-3">
                <label for="last_name">Last Name</label>
                <input type="text" name="last_name" class="form-control" id="last_name" value="{{request.user.last_name}}" readonly>
            </div>
            <div class="form-group pt-3">
                <label for="email">Email</label>
                <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp"
                    placeholder="Enter email" required>
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                    else.</small>
            </div>

            <div class="form-group">
                <label for="phone">Phone Number</label>
                <input type="tel" name="phone" class="form-control" id="phone" placeholder="Enter your phone number" required>
            </div>

            <div class="form-group">
                <label class="form-label d-block" for="profileimg">Upload Your Profile Photo</label>
                <input type="file" name="profileimg" id="profileimg" accept="image/png, image/jpeg, image/jpg"/>
            </div>
            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>
</section>
{% endblock content %}

home/templates/email_confirmation.html
{% autoescape off %}

Welcome to Car Sharing Service!!
Hello {{ name }}!!
Please confirm your email by clicking on the following link.

Confirmation Link: http://{{ domain }}{% url 'home:activate' uidb64=uid token=token %} 

{% endautoescape %}

home/templates/logIn.html
{% extends 'base.html' %}
{% load static %}

  {% block head %}
  <title>Log In</title>
  <!-- CSS script -->
  <link rel="stylesheet" href="{% static 'LogIn.css' %}" />
  {% endblock head %}

  {% block content %}
  <section class="bg-image">
    <div class="mask d-flex align-items-center py-5">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px">
              <div class="card-body p-5">
                <h2 class="text-uppercase text-center mb-5">Log In</h2>

                <form method="POST">
                  {% csrf_token %}

                  <div class="form-outline mb-4">
                    <label class="form-label" for="username">Username</label>
                    <input type="text" name="username" id="username" class="form-control form-control-lg" />
                  </div>

                  <div class="form-outline mb-4">
                    <label class="form-label" for="form3Example4cg">Password</label>
                    <input type="password" name="pass1" id="form3Example4cg" class="form-control form-control-lg" />
                  </div>

                  <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary btn-block btn-lg gradient-custom-4 text-body">
                      Login
                    </button>
                  </div>

                  <p class="text-center text-muted mt-3">
                    New User ?
                    <a href="{% url 'home:register' %}" class="fw-bold text-body"><u>Register</u></a>
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}

home/templates/logOut.html
{% extends 'base.html' %}
{% block head %}{% endblock %}
{% block content %} {% endblock %}

home/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark {% if profile.image != NULL and profile.image.url %}py-0{% endif %}" style="z-index: 1">
  <a class="navbar-brand" href="{% url 'home:home' %}">CarSharing</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent"
    aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item {% block homeactive %}{% endblock homeactive %}">
        <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% block rideactive %}{% endblock rideactive %}">
        <a class="nav-link" href="{% url 'home:pickRide' %}">Pick Your Ride</a>
      </li>
      <li class="nav-item {% block allRidesactive %}{% endblock allRidesactive %}">
        <a class="nav-link" href="{% url 'home:rides' %}">All Rides</a>
      </li>
      <li class="nav-item {% block contactactive %}{% endblock contactactive %}">
        <a class="nav-link" href="{% url 'home:contact' %}">Contact</a>
      </li>
    </ul>
    <div>
      {% if user.is_authenticated %}
      <ul class="navbar-nav mr-3">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {% if profile.image != NULL and profile.image.url %}
          <img src="{{profile.image.url}}" alt="Profile Image" width="40" height="40" style="border-radius: 100%">
          {% else %}
            Welcome {{request.user.first_name}}!
          {% endif %}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" {% if profile.image != NULL and profile.image.url %}style="left: -90%"{% endif %}>
            <a class="dropdown-item" href="{% url 'home:profile' request.user%}">Profile</a>
            <a class="dropdown-item" href="{% url 'home:editProfile' %}">Edit your Profile</a>
            <a class="dropdown-item" href="{% url 'home:PubRide' %}">Publish A Ride</a>
            <a class="dropdown-item" href="{% url 'home:yourRide' request.user.id %}">Your Rides</a>
            <a class="dropdown-item" href="{% url 'home:booking' request.user.id %}">Your Bookings</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'home:logOut' %}">Sign Out</a>
          </div>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav mr-3">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:logIn' %}"><i class="fa-solid fa-right-to-bracket nav-icon"></i>Log
            In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:register' %}"><i class="fa-solid fa-user nav-icon"></i>Register</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

home/templates/pickRide.html
{% extends 'base.html' %}

{% load static %}

{% block head %}
<title>Pick Your Ride</title>
{% endblock head %}

{% block rideactive %}active{% endblock rideactive %}

{% block content %}
<section id="pickRide">
    <div class="container d-block my-2 px-0 pb-5">
        <h2 class="py-3">Pick your Ride</h2>
        <form name="ChooseRideForm" action="{% url 'home:rides' %}" method="post" class="text-left">
            {% csrf_token %}
            <div class="form-group">
                <label for="leave">From</label>
                <input type="text" class="form-control" id="leave" name="leave" placeholder="Leaving From..."
                    required>
            </div>
            <div class="form-group">
                <label for="arrive">To</label>
                <input type="text" class="form-control" id="arrive" name="arrive" placeholder="Going To..."
                    required>
            </div>
            <div class="form-group">
                <!-- Input field along with
                calendar icon and -->
                <!-- <div class="input-group date "> -->
                    <!-- Sets the calendar icon -->
                    <!-- <span class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fa fa-calendar calenderIcon"></i>
                        </span>
                    </span> -->
                    <!-- Accepts the input from calendar -->
                    <label for="date">Date</label>
                    <input class="form-control" type="date" placeholder="Depature date..." name="date">
                <!-- </div> -->
            </div>
            <div class="form-group">

                <label for="number">No. of Passengers</label>
                <div class="input-group number-spinner">
                    <span class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fa-solid fa-circle-minus" data-dir="dwn"></i>
                        </span>
                    </span>
                    <input type="number" class="form-control" placeholder="No. of Passengers"
                        autocomplete="off" name="number" oninput="validity.valid||(value='');" min="0" step="1" maxlength="10">
                    <span class="input-group-prepend" data-dir="up">
                        <span class="input-group-text">
                            <i class="fa-solid fa-circle-plus"></i>
                        </span>
                    </span>
                </div>
            </div>
            <button type="submit" class="btn btn-outline-info">Search</button>
        </form>
    </div>
</section>
{% endblock content %}

home/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Profile Info</title>
{% endblock %}

{% block content %}
<section id="profile-info">
    <div class="container profile my-3 pb-4">
        <h2>Profile Information</h2>
        {% if profile.image != NULL and profile.image.url %}
        <div class="row profileimage text-center">
            <div class="col-12 my-3">
                {% if profile.image != NULL and profile.image.url %}
                <img src="{{profile.image.url}}" alt="Profile Image" width="250" height="250" style="border-radius: 100%">
                {% endif %}
            </div>
        </div>
        {% endif %}
        <div class="profilecontent">
            <h4>Username:- <span class="text-muted">{{profile.user}}</span></h4>
            <h4>Name:- <span class="text-muted">{{profile.first_name}} {{profile.last_name}}</span></h4>
            <h4>Email:- <span class="text-muted">{{profile.email}}</span></h4>
            <h4>Contact Number:- <span class="text-muted">{{profile.contact_no}}</span></h4>
        </div>
    </div>
</section>
{% endblock content %}

home/templates/register.html
{% extends 'base.html' %} 

{% load static %}

{% block head %}
<title>Register</title>
<!-- CSS script -->
<link rel="stylesheet" href="{% static 'Register.css' %}" />
{% endblock %}

{% comment %} <body onload="resetting()"> {% endcomment %}
  {% block content %}
  <section class="signup-title bg-image">
    <div class="container-fluid h-custom">
      <h2 class="py-5">Register</h2>
      <div class="row d-flex justify-content-center align-items-center text-left h-100">
        <div class="col-md-8 col-lg-6 col-xl-4">
          <form name="form" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="form-outline mb-4 col-md-6">
                <label class="form-label" for="first_name">First Name</label>
                <input type="text" name="first_name" id="first_name" class="form-control form-control-lg"
                  placeholder="Enter First Name" />
              </div>
              <div class="form-outline mb-4 col-md-6">
                <label class="form-label" for="last_name">Last Name</label>
                <input type="text" name="last_name" id="last_name" class="form-control form-control-lg"
                  placeholder="Enter Last Name" />
              </div>
            </div>

            <div class="form-outline mb-4">
              <label class="form-label" for="email">Your Email</label>
              <input type="email" name="email" id="email" class="form-control form-control-lg"
                placeholder="abc@gmail.com" />
            </div>

            <div class="form-outline mb-4">
              <label class="form-label" for="username">Username</label>
              <input type="text" name="username" id="username" class="form-control form-control-lg"
                placeholder="Enter username" />
            </div>

            <div class="form-outline mb-4">
              <label class="form-label" for="pass1">Password</label>
              <input type="password" name="pass1" id="pass1" class="form-control form-control-lg" />
            </div>

            <div class="form-outline mb-4">
              <label class="form-label" for="pass2">Repeat your password</label>
              <input type="password" name="pass2" id="pass2" class="form-control form-control-lg" />
            </div>
            <div class="form-check d-flex justify-content-center mb-5">
              <input type="checkbox" class="form-check-label" id="checkit" />
              <label class="form-check-label" for="checkit">
                I agree all statements in
                <a href="#!" class="text-body"><u>Terms of service</u></a>
              </label>
            </div>

            <div class="d-flex justify-content-center">
              <button type="submit" class="btn btn-info btn-block btn-lg">
                Register
              </button>
            </div>

            <p class="text-center text-muted mt-3">
              Have already an account?
              <a href="{% url 'home:logIn' %}" class="fw-bold text-body"><u>Login here</u></a>
            </p>
          </form>
        </div>
      </div>
    </div>
  </section>

  <script src="{% static 'Register.js' %}"></script>
  {% endblock %}

home/templates/rides.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Rides Search Results</title>
<!-- CSS script -->
<link rel="stylesheet" href="{% static 'rides.css' %}" />
{% endblock head %}

{% block content %}
<div class="container">
  <h2 class="my-3 d-flex">Your search rides results:- </h2>
  {% include 'rideCards.html' %}
</div>
{% endblock %}